### ISSUE TITLE
没有go语言基础，请问该程序如何搭建

### ISSUE THREAD

**Issue by a8196168** [gufeijun/baiduwenku-go#1]
正在学习web程序，发现go语言还能做网站，贵程序搭建跟PHP不一样，我服务器只安装了个宝塔，请问怎样才能运行baiduwenku-go这个程序！希望能做一下详细步骤和搭建教程，感激不尽

**Comment by 2d7** [comment]
不需要go语言基础，会点数据库就行，你可以看看我这个http://2d7.top/archives/%E8%AE%B0%E4%B8%80%E6%AC%A1%E7%99%BE%E5%BA%A6%E6%96%87%E5%BA%93%E8%A7%A3%E6%9E%90%E5%B9%B3%E5%8F%B0%E7%9A%84%E6%90%AD%E5%BB%BA

**Comment by a8196168** [comment]
> 不需要go语言基础，会点数据库就行，你可以看看我这个http://2d7.top/

我的linux服务器搭建出来了，注册完前台登录后不显示已登录，也不能登录后有3次下载机会

**Comment by gufeijun** [comment]
不显示登录的原因是配置文件中DOMAIN设置错误，不应该为0.0.0.0，而应该是域名或具体公网IP，只有这样浏览器才会将COOKIE给提交。
已更新docker支持，配置文件增加了REGEXP，可通过正则指定哪些邮箱能下载转向文档。

**Comment by a8196168** [comment]
> 不显示登录的原因是配置文件中DOMAIN设置错误，不应该为0.0.0.0，而应该是域名或具体公网IP，只有这样浏览器才会将COOKIE给提交。
> 已更新docker支持，配置文件增加了REGEXP，可通过正则指定哪些邮箱能下载转向文档。

不显示登录是我自己弄错了，现在已经没有问题！大部分人群用的都是qq邮箱，怎样取消下载次数的限制呢

**Comment by a8196168** [comment]
多个个不同的用户解析同一链接，第一个用户解析完，其他用户再解析，有时会出现错误状态

**Comment by gufeijun** [comment]
已经修复你说的这个bug，至于取消下载限制，**两种解决办法**：

①用户注册时会根据配置文件中的REGEXP规则来决定其permissioncode是否为1，为1既可以不限量下载也包含专享文档下载权限。所以只需要将配置文件的REGEXP改成`.*`即可(匹配所有邮箱)，但这样做也会导致让**所有人**都含有专享文档下载权限。如果这么做还需要将已经注册用户的permissioncode手动改为1，当然也可以直接删除所有用户让其重新注册。

②如果既想保留对专享文档的限制功能又想取消限量下载，可以将[OperateController.go](https://github.com/gufeijun/baiduwenku-go/blob/master/controller/OperateController.go)下的这两处位置注释掉，然后重新编译运行即可。
![LH27SQZM8OXPL1L$37@}1YT](https://user-images.githubusercontent.com/48559547/87383816-e25d7f80-c5cc-11ea-9312-8e0362c35003.png)
![TIM图片20200714121050](https://user-images.githubusercontent.com/48559547/87383820-e38eac80-c5cc-11ea-9042-49756285924c.png)

**Comment by a8196168** [comment]
> 已经修复你说的这个bug，至于取消下载限制，**两种解决办法**：
> 
> ①用户注册时会根据配置文件中的REGEXP规则来决定其permissioncode是否为1，为1既可以不限量下载也包含专享文档下载权限。所以只需要将配置文件的REGEXP改成`.*`即可(匹配所有邮箱)，但这样做也会导致让**所有人**都含有专享文档下载权限。如果这么做还需要将已经注册用户的permissioncode手动改为1，当然也可以直接删除所有用户让其重新注册。
> 
> ②如果既想保留对专享文档的限制功能又想取消限量下载，可以将[OperateController.go](https://github.com/gufeijun/baiduwenku-go/blob/master/controller/OperateController.go)下的这两处位置注释掉，然后重新编译运行即可。
> ![LH27SQZM8OXPL1L$37@}1YT](https://user-images.githubusercontent.com/48559547/87383816-e25d7f80-c5cc-11ea-9312-8e0362c35003.png)
> ![TIM图片20200714121050](https://user-images.githubusercontent.com/48559547/87383820-e38eac80-c5cc-11ea-9042-49756285924c.png)

谢谢指导，希望后期能加上后台管理，基本设置，比如限制用户登录，设定用户可下载次数，这样管理起来就方便多了，祝大佬永无BUG！
