### ISSUE TITLE
都是 No Submatch 

### ISSUE THREAD

**Issue by carlchina** [gufeijun/baiduwenku-go#4]
填了 4 个文档的地址都是 提示 No Submatch 不知道什么意思

**Comment by gufeijun** [comment]
很大概率链接填错了，能给个你输入的链接的样例吗

**Comment by carlchina** [comment]
https://wenku.baidu.com/view/30f97850edf9aef8941ea76e58fafab068dc4475.html

**Comment by gufeijun** [comment]
文库前端更新了，要重写代码，哎
